### ISSUE TITLE
 browser.getUI5Version is not a function

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#195]
**Describe the bug**
Error raised on execution of **injectUI5()**

**To Reproduce**

```js
    await browser.url(baseUrl)
    const { default: _ui5Service } = require("wdio-ui5-service")
    const ui5Service = new _ui5Service()
    await ui5Service.injectUI5()
```

**Expected behavior**
The spec to run successfully 

**Logs/Console Output**
```cmd
TypeError: browser.getUI5Version is not a function
    at C:\Users\myUser\git\myProject\node_modules\wdio-ui5-service\src\lib\wdi5-bridge.ts:104:38
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version:  "0.9.0-rc1"

**Comment by vobu** [comment]
hm, as we're constantly running a test that explicitly does exactly what you're describing (https://github.com/js-soft/wdi5/blob/main/examples/ui5-js-app/webapp/test/e2e/ui5-late.test.js), I wonder whether the app that you're serving and trying to run `wdi5` on is actually a UI5 app at all?

**Comment by nair-sumesh** [comment]
🤣 yes it is. The flp home page is already loaded and displayed before **injectUI5** is being invoked. 

Until this point wdio methods are used to serve the login credentials.

Just fyi, I have the config baseurl and wdi5.url as empty string.

**Comment by dominikfeininger** [comment]
Hi, related to https://github.com/js-soft/wdi5/issues/122 ?

**Comment by nair-sumesh** [comment]
Thanks @dominikfeininger, however I followed everything as you mentioned. In fact the same code works in  0.8.1v and fails in 0.9.0-rc1v

**Comment by dominikfeininger** [comment]
Can you please change your wdi5 loglevel to `verbose` I guess you can then see this message: `open url with fallback '#' (this is not causing any issues since its is removed for navigation)` . Which causes the trouble with the FLP.

If not please provide the full `verbose` log.

**Comment by nair-sumesh** [comment]
Yes I can view this message. Is the error because this behaviour. I was about to create another issue about why does this message is being raised when I have set the config param **skipInjectUI5OnStart** to **true**.

In my test, I don't wish to start the test with any url as such. At one point of time the url will be passed/populated dynamically from the code. Until then I would like to keep the chrome driver's url empty.

This was possible with previous versions.

**Comment by nair-sumesh** [comment]
Hi @dominikfeininger,

You are correct.
When I provide a non empty `wdi5.url`, then the test passes successfully.
However, when kept empty, I encounter errors like 
- `open url with fallback '#' (this is not causing any issues since its is removed for navigation)`
- `browser.asControl is not a function`
- 'browser.getUI5Version is not a function'

As a workaround, I keep the parameter `wdi5.url` non-empty. 
However, it would be really appreciated if this limitation can be resolved.

**Comment by vobu** [comment]
> As a workaround, I keep the parameter `wdi5.url` non-empty. However, it would be really appreciated if this limitation can be resolved.

Since you've contributed before to `wdi5` (thanks again 🙌 ), why not give this a shot via a PR 🤗 ?
